# -------------------
# Builder Stage
# -------------------
FROM node:22-alpine AS builder

WORKDIR /app/haribon

# Install dependencies
COPY package.json package-lock.json nx.json tsconfig.* ./
RUN npm install

# Copy Prisma schema & generate client (shared lib)
COPY prisma ./prisma/
RUN npx prisma generate

# Copy the workspace files
COPY . .

# Build only this service
RUN npx nx build road-network-service

# -------------------
# Runner Stage
# -------------------
FROM node:22-alpine AS runner

WORKDIR /app/haribon

# Copy only necessary files from builder
COPY --from=builder /app/haribon/dist/apps/map-service/road-network-service ./dist/map-service/road-network-service
COPY --from=builder /app/haribon/node_modules ./node_modules
COPY --from=builder /app/haribon/package.json ./package.json

ENV NODE_ENV=production
EXPOSE 3009

CMD ["node", "dist/map-service/road-network-service/main.js"]

