services:
    authentication-service:
        image: martin09123/project-haribon:authentication-service
        container_name: haribon-authentication-service
        ports:
            - '3001:3001'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
    user-service:
        image: martin09123/project-haribon:user-service
        container_name: haribon-user-service
        ports:
            - '3003:3003'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
    warehouse-service:
        image: martin09123/project-haribon:warehouse-service
        container_name: haribon-warehouse-service
        ports:
            - '3004:3004'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
    dispensing-point-service:
        image: martin09123/project-haribon:dispensing-point-service
        container_name: haribon-dispensing-point-service
        ports:
            - '3005:3005'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
    rescue-post-service:
        image: martin09123/project-haribon:rescue-post-service
        container_name: haribon-rescue-post-service
        ports:
            - '3006:3006'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
    activity-log-service:
        image: martin09123/project-haribon:activity-log-service
        container_name: haribon-activity-log-service
        ports:
            - '3007:3007'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
    mailer-service:
        image: martin09123/project-haribon:mailer-service
        container_name: haribon-mailer-service
        ports:
            - '3008:3008'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
    road-network-service:
        image: martin09123/project-haribon:road-network-service
        container_name: haribon-road-network-service
        ports:
            - '3009:3009'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
    role-service:
        image: martin09123/project-haribon:role-service
        container_name: haribon-role-service
        ports:
            - '3010:3010'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
