# -------------------
# Builder Stage
# -------------------
FROM node:22-alpine AS builder

RUN apk add --no-cache openssl

# Set working directory
WORKDIR /app

# Set Nx Cloud Token as ARG
ARG NX_CLOUD_ACCESS_TOKEN
ENV NX_CLOUD_ACCESS_TOKEN=${NX_CLOUD_ACCESS_TOKEN}

COPY package.json package-lock.json nx.json tsconfig* ./

RUN npm ci

# Copy Prisma schema and generate client
COPY prisma ./prisma/
RUN npx prisma generate

COPY . .

# Disable Nx Daemon
# ENV NX_DAEMON=false

RUN npm run build:all

# -------------------
# Runner Stage
# -------------------
FROM node:22-alpine AS runner

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY --from=builder /app/package.json /app/package-lock.json ./

# Copy built files and node_modules from builder
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules

ENV NODE_ENV=production

EXPOSE 3001 3002 3003 3004 3005 3006 3007 3008 3009

CMD ["npm", "run", "start:all:production"]
