import SessionComponentProvider from '../context/session-provider';
import './global.css';

export const metadata = {
    title: 'Welcome to web-app',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <SessionComponentProvider>
                    <main>{children}</main>
                </SessionComponentProvider>
            </body>
        </html>
    );
}
