import SessionComponentProvider from '../context/session-provider';
import './global.css';

import { SessionProvider } from 'next-auth/react';

export const metadata = {
    title: 'Welcome to web-app',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <SessionComponentProvider>
                <body>{children}</body>
            </SessionComponentProvider>
        </html>
    );
}
