import { ThemeProvider } from '@b-prism/shadcn-ui/index';
import SessionComponentProvider from '../context/session-provider';
import './global.css';

export const metadata = {
    title: 'Welcome to web-app',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className='overflow-hidden'>
                <SessionComponentProvider>
                    <ThemeProvider
                        attribute='class'
                        defaultTheme='system'
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                    </ThemeProvider>
                </SessionComponentProvider>
            </body>
        </html>
    );
}
