'use client';

import { SessionProvider } from 'next-auth/react';
import './global.css';

// export const metadata = {
//     title: 'Welcome to b-prism',
//     description: 'Generated by create-nx-workspace',
// };

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <SessionProvider>
                <body>{children}</body>
            </SessionProvider>
        </html>
    );
}
