import './global.css';
import SessionLayout from './session-layout';

export const metadata = {
    title: 'Welcome to b-prism',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <SessionLayout>{children}</SessionLayout>
            </body>
        </html>
    );
}
