name: Docker Image CI

on:
    push:
        branches: ['production']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Docker Compose
              run: sudo apt-get update && sudo apt-get install -y docker-compose

            - name: Login to Dockerhub
              env:
                  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
                  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            - name: Check directory
              run: ls -R

            - name: Build the Docker image
              run: docker-compose -f docker-compose.prod.yml build

            - name: Tag the image
              run: docker tag haribon-microservices martin09123/haribon-microservices:latest

            - name: Push the image to Dockerhub
              run: docker push martin09123/haribon-microservices:latest
